print("scientist profile")
print("===================================")
print("name: albert einstein")
print("born: 14th march 1879")
print("died: 18th April 1955")
print("===================================")
print("field: theoretical physics")
print("known for: theory of relativity, photoelectric effect, mass-energy equivalence")
print("awards: nobel prize in physics (1921), copley medal (1925), max planck medal (1929)")
print("contributions: special and general relativity, quantum theory, brownian motion, unified field theory")
print("====================================")
print("interesting facts:")
print("1. einstein was offered the presidency")
print("2. he was a pacifist and civil rights advocate")
print("3. he had a great sense of humor")
print("====================================")
print("quote: 'imagination is more important than knowledge. for knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.'")
print("====================================")
print("====================================")