print("hello world!")
print("Student Profile")
print("name: Ananth")
print("age: 15")
print("grade: 10")
print("school: Gems Welington School Qatar")
print("hobbies: swimming, cricket, badminton, table tennis, basketball and much more! ")
print("ambition: to become an aerospace engineer for the army")
print("favourite subjects: physics, chemistry, math, design technology, computer science and spanish")
